### PR TITLE
Improving logic for install script

### PR DESCRIPTION
**Pull request by proffapt**
This is how it will look!

image

### CODE REVIEW

**Review by tashima42 — COMMENTED** [review]
I really like the looks and organization of the script, I'd just like to clarify something:
What would be the install instructions using this script? To install the scripts people would need to clone the repo?

**Comment by proffapt** [comment]
> I really like the looks and organization of the script, I'd just like to clarify something: What would be the install instructions using this script? To install the scripts people would need to clone the repo?

Yeah, that's how github repos work.. I can see you that wanted a script which will be self-sufficient in itself, right?

I prefer this way of installation over the other, because the user has atleast somewhat control over the process, can read the installation script; which is not the case with this approach of installation.

**Comment by tashima42** [comment]
I was trying to make installation as easy as possible for people that aren't that familiar with the cli, git, etc. But I think it's very unlikely that someone that isn't familiar with the CLI will use this, and this method has some advantages, so I'm merging it. Thanks for the contribution.

**Comment by proffapt** [comment]
Great.

**Pull request merged**
